--user: utente
--password: utente

CREATE DATABASE Nerdbook;

CREATE TABLE utenti(
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome VARCHAR(256),
	cognome VARCHAR(256),
	eMail VARCHAR(256),
	urlFoto VARCHAR(256),
	frase VARCHAR(256),
	password VARCHAR(256)
);

CREATE TABLE gruppi(
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome VARCHAR(256),
	urlFoto VARCHAR(256)
);



CREATE TABLE posts(
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	autore INTEGER,
	bacheca_ut INTEGER,
	gruppo INTEGER,
	contenuto VARCHAR(1024),
	tipo INTEGER,
	allegato VARCHAR(256),
	FOREIGN KEY (autore) REFERENCES utenti(id),
	FOREIGN KEY (bacheca_ut) REFERENCES utenti(id),
	FOREIGN KEY (gruppo) REFERENCES gruppi (id)
);


CREATE TABLE amici(
	id1 INTEGER,
	id2 INTEGER,
	FOREIGN KEY (id1) REFERENCES utenti(id),
	FOREIGN KEY (id2) REFERENCES utenti(id),
	PRIMARY KEY (id1, id2)
);

CREATE TABLE membri(
	 

	FOREIGN KEY (id1) REFERENCES gruppi(id),
	FOREIGN KEY (id2) REFERENCES utenti(id),
	PRIMARY KEY (id1, id2)
);

INSERT INTO utenti (id, nome, cognome, eMail, urlFoto,  frase, password) VALUES (default, 'Giovanni ', 'Masala', 'masala@gmail.com', 'img/giovanni.jpg','Ciao Giovani!', 'aaa');
INSERT INTO utenti (id, nome, cognome, eMail, urlFoto,  frase, password) VALUES (default, 'Gianni', 'sperti', 'gianni@gmail.com', 'img/sperti.jpg',  'Allegria!', 'aaa');
INSERT INTO utenti (id, nome, cognome, eMail, urlFoto,  frase, password) VALUES (default, 'Ronaldinho', 'Gaucho', 'dinho@gmail.com', 'img/dinho.jpg',  'joga bonito', 'aaa');

--Esempio utente senza nome che verrà inoltrato direttamente nel profilo
INSERT INTO utenti (id, nome, cognome, eMail, urlFoto,  frase, password) VALUES (default, 'SenzaCognome', null, 'noSurname@gmail.com', 'img/unknown.jpg',  'noSurname', 'aaa');




INSERT INTO gruppi (id, nome, urlFoto) VALUES (default, 'Calciatori', 'img/calcio.jpg');
INSERT INTO gruppi (id, nome, urlFoto) VALUES (default, 'Ballerini', 'img/danza.jpg');
INSERT INTO gruppi (id, nome, UrlFoto) VALUES (default, 'Grafici', 'img/mac.jpg');

INSERT INTO posts (id, autore, bacheca_ut, gruppo, contenuto, tipo, allegato) VALUES (default, 1, 1, null, 'Ciao a tutti! Sono il miglior Masala!', 1, null);
INSERT INTO posts (id, autore, bacheca_ut, gruppo, contenuto, tipo, allegato) VALUES (default, 2, 2, null, 'Apriamo le danze', 3, 'img/kledi.jpg');
INSERT INTO posts (id, autore, bacheca_ut, gruppo, contenuto, tipo, allegato) VALUES (default, 3, 3, null, 'Umilio tutti', 2, 'https://it.wikipedia.org/wiki/Ronaldinho');

INSERT INTO amici (id1, id2) VALUES (1, 2);
INSERT INTO amici (id1, id2) VALUES (2, 1);
INSERT INTO amici (id1, id2) VALUES (1, 3);
INSERT INTO amici (id1, id2) VALUES (3, 1);
INSERT INTO amici (id1, id2) VALUES (2, 3);
INSERT INTO amici (id1, id2) VALUES (3, 2);

INSERT INTO membri (id1, id2) VALUES (1, 1);
INSERT INTO membri (id1, id2) VALUES (1, 2);
INSERT INTO membri (id1, id2) VALUES (1, 3);
INSERT INTO membri (id1, id2) VALUES (2, 1);
INSERT INTO membri (id1, id2) VALUES (2, 2);
INSERT INTO membri (id1, id2) VALUES (2, 3);
INSERT INTO membri (id1, id2) VALUES (3, 1);
INSERT INTO membri (id1, id2) VALUES (3, 2);
INSERT INTO membri (id1, id2) VALUES (3, 3);







